name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # container:
    #     image: docker://pandoc/core:3.1-ubuntu

    steps:
      - name: Check git
        run: |
          git --version
          
      # TODO: maybe it makes sense to make a public docker container and use it instead... especially if this gets more complicated
      - name: Install Pandoc
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends pandoc
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Prebuild listing of files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run make
        run: |
          make all

      - name: Postbuild listing of files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Archive the output files
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build
            