name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
        image: docker://pandoc/core:3.1-ubuntu

    steps:
      - name: Check if pandoc container is working
        run: |
          pandoc --version
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
