name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # container:
    #     image: docker://pandoc/core:3.1-ubuntu

    steps:
      - name: Check git
        run: |
          git --version

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: pandoc/core:3.1-ubuntu
            run: |
                pandoc --version

      # - name: Check if pandoc container is working
      #   uses: docker://pandoc/core:3.1-ubuntu
      #   with:
      #     entrypoint: pandoc
      #     avg: --version
        # run: |
          # pandoc --version

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
