name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # container:
    #     image: docker://pandoc/core:3.1-ubuntu

    steps:
      - name: Check git
        run: |
          git --version

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Prebuild listing of files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: pandoc/core:3.1-ubuntu
            run: |
              apt-get install -y make
              make --version

      - name: Postbuild listing of files in the repository
        run: |
          ls ${{ github.workspace }}
