name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # container:
    #     image: docker://pandoc/core:3.1-ubuntu

    steps:
      - name: Check git
        run: |
          git --version
          
      - name: Install Pandoc
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends pandoc
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Prebuild listing of files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run make
        run: |
          make all
        # uses: addnab/docker-run-action@v3
        # with:
        #     image: pandoc/core:3.1-ubuntu
        #     run: |
        #       apt-get update
        #       apt-get install -y make
        #       pwd
        #       cd ${{ github.workspace }}
        #       pwd
        #       make all

      - name: Postbuild listing of files in the repository
        run: |
          ls ${{ github.workspace }}
